<?php

/**
 * Attach the library admin_styles/claro if the library claro/global-styling is attached.
 */
function admin_styles_library_info_alter(&$libraries, $extension) {
  $module_path = '/' . \Drupal::service('extension.list.module')
    ->getPath('admin_styles') . '/css';
  // Attach custom-bootstrap-grid.min.css and claro.min.css to the claro theme.
  if ($extension === 'claro' && isset($libraries['global-styling'])) {
    $libraries['global-styling']['css']['theme'][$module_path . '/custom-bootstrap-grid.min.css'] = ['minified' => TRUE];
    $libraries['global-styling']['css']['theme'][$module_path . '/claro.min.css'] = ['minified' => TRUE];
  }
  // Attach admin-toolbar.min.css to the admin_toolbar module.
  if ($extension === 'admin_toolbar' && isset($libraries['toolbar.tree'])) {
    $libraries['toolbar.tree']['css']['theme'][$module_path . '/admin-toolbar.min.css'] = ['minified' => TRUE];
  }
  // Attach frontend-editing.min.css to the frontend_editing module.
  if ($extension === 'frontend_editing' && isset($libraries['frontend_editing'])) {
    $libraries['frontend-editing']['css']['theme'][$module_path . '/frontend-editing.min.css'] = ['minified' => TRUE];
  }
}
